# Generated by Django 3.2 on 2021-04-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_room_guese_can_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_can_pause',
            field=models.BooleanField(default=False),
        ),
    ]
